# Generated by Django 4.2.21 on 2026-05-21 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="手机号"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="个人简介")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户扩展信息",
                "verbose_name_plural": "用户扩展信息",
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="LectureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                (
                    "color",
                    models.CharField(
                        default="#5c4d82", max_length=20, verbose_name="分类颜色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "讲义分类",
                "verbose_name_plural": "讲义分类",
                "db_table": "lecture_category",
                "ordering": ["-created_at"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="LectureArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="讲义标题")),
                (
                    "subject",
                    models.CharField(blank=True, max_length=100, verbose_name="科目"),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="videos/",
                        verbose_name="原始视频",
                    ),
                ),
                ("summary_file", models.TextField(blank=True, verbose_name="总结内容")),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="pdfs/", verbose_name="PDF文件"
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="标签"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "处理失败"),
                        ],
                        default="processing",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "processing_params",
                    models.JSONField(blank=True, default=dict, verbose_name="处理参数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lectures",
                        to="app.lecturecategory",
                        verbose_name="所属分类",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "讲义存档",
                "verbose_name_plural": "讲义存档",
                "db_table": "lecture_archive",
                "ordering": ["-created_at"],
            },
        ),
    ]
