# Generated by Django 4.2.21 on 2026-05-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrameImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_index", models.IntegerField(verbose_name="帧索引")),
                ("timestamp", models.FloatField(verbose_name="时间戳(秒)")),
                (
                    "image_file",
                    models.ImageField(upload_to="frames/", verbose_name="帧图片"),
                ),
                ("ocr_text", models.TextField(blank=True, verbose_name="OCR识别文本")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frame_images",
                        to="app.lecturearchive",
                        verbose_name="所属讲义",
                    ),
                ),
            ],
            options={
                "verbose_name": "帧图片",
                "verbose_name_plural": "帧图片",
                "db_table": "frame_image",
                "ordering": ["frame_index"],
            },
        ),
    ]
