# Generated by Django 4.2.21 on 2026-06-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_frameimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="frameimage",
            name="image_content_type",
            field=models.CharField(
                default="image/jpeg", max_length=50, verbose_name="图片类型"
            ),
        ),
        migrations.AddField(
            model_name="frameimage",
            name="image_data",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="图片二进制数据"
            ),
        ),
        migrations.AlterField(
            model_name="frameimage",
            name="image_file",
            field=models.ImageField(
                blank=True, null=True, upload_to="frames/", verbose_name="帧图片"
            ),
        ),
    ]
